data_transformation:
  split_size: 0.2
  random_state: 268

model_training:

  vocabulary_size: 30552
  num_layers: 4
  num_heads: 4
  hidden_dim: 256
  intermediate_dim: 512
  max_sequence_length: 128

  sequence_length: 128

  activation: softmax
  labels_count: 2
  metric1: sparse_categorical_accuracy
  metric2: precision
  metric3: recall

  batch_size: 1
  epochs: 1
  shuffle: true
